project_id = "oeltgtllcxynhoirbfey"

[functions.generate-questions]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.grade-exam]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
